### ISSUE TITLE
abp集成IdentityServer4和单点登录

### ISSUE THREAD

**Issue by lx4556332** [dashenxian/XSX.Captcha#1]
你好，这个项目的源码你那边有吗？麻烦提供参考下，万分感谢。
https://dashenxian.github.io/post/abp%E9%9B%86%E6%88%90IdentityServer4%E5%92%8C%E5%8D%95%E7%82%B9%E7%99%BB%E5%BD%95.html

**Comment by dashenxian** [comment]
原文链接下有代码链接https://gitee.com/XiaoShenXiana/abp_ids4.git

**Comment by lx4556332** [comment]
Think you!
